#pragma once
#include <Windows.h>
#include <cstddef>
#include <string>

namespace ExtendedOptions
{
    struct OptionStrings
    {
        std::wstring strExtendedOptions;
        std::wstring strGodMode;
        std::wstring hintGodMode;
        std::wstring strHighJump;
        std::wstring hintHighJump;
        std::wstring strSheepHeaven;
        std::wstring hintSheepHeaven;
        std::wstring strSuperShopperCrates;
        std::wstring hintSuperShopperCrates;
        std::wstring strExtendedFusesHerds;
        std::wstring hintExtendedFusesHerds;
        std::wstring strUtilitiesDontEndTurn;
        std::wstring hintUtilitiesDontEndTurn;
        std::wstring strWeaponsDontEndTurn;
        std::wstring hintWeaponsDontEndTurn;
        std::wstring strLossOfControlDoesntEndTurn;
        std::wstring hintLossOfControlDoesntEndTurn;
        std::wstring strWormSelectAfterMovement;
        std::wstring hintWormSelectAfterMovement;
        std::wstring strLowGravity;
        std::wstring hintLowGravity;
        std::wstring strPersistentRope;
        std::wstring hintPersistentRope;
        std::wstring strRapidPlay;
        std::wstring hintRapidPlay;
        std::wstring strIndestructibleTerrain;
        std::wstring hintIndestructibleTerrain;
        std::wstring strInvisibleTerrain;
        std::wstring hintInvisibleTerrain;
        std::wstring strFastCrates;
        std::wstring hintFastCrates;
        std::wstring strCrateSpy;
        std::wstring hintCrateSpy;
        std::wstring strCrateLimit;
        std::wstring hintCrateLimit;
        std::wstring strCrateRate;
        std::wstring hintCrateRate;
        std::wstring strSuicideBomber;
        std::wstring hintSuicideBomber;
        std::wstring strAquaSheep;
        std::wstring hintAquaSheep;
        std::wstring strInstantMines;
        std::wstring hintInstantMines;
        std::wstring strHerd;
        std::wstring hintHerd;
        // All four derived herd captions use hintHerd.
        std::wstring strHerdDynamite;
        std::wstring strHerdMine;
        std::wstring strHerdMingVase;
        std::wstring strHerdSheep;
        std::wstring strDisableBackflip;
        std::wstring hintDisableBackflip;
        std::wstring strDisableUnlockedAim;
        std::wstring hintDisableUnlockedAim;
    };

    inline std::wstring OptionResourceString(HMODULE resourceModule, UINT stringId)
    {
        wchar_t text[256]{};
        LoadStringW(resourceModule, stringId, text, 256);
        return text;
    }

    // Fill each language case below. Blank translations intentionally remain blank.
    inline OptionStrings MakeOptionStrings(const std::string& language, HMODULE resourceModule)
    {
        OptionStrings strings{};
        const char* const languages[] = {
            "cs", "de", "en", "es", "es-419", "fr", "is", "it", "nl", "pl", "pt", "pt-br", "ru", "sv", "zh-Hans"
        };
        std::string code = language;
        if (code.compare(0, 3, "\xEF\xBB\xBF") == 0) code.erase(0, 3);
        const auto first = code.find_first_not_of(" \t\r\n");
        code = first == std::string::npos ? std::string{} :
            code.substr(first, code.find_last_not_of(" \t\r\n") - first + 1);
        size_t languageIndex = 2; // English fallback.
        for (size_t i = 0; i < sizeof(languages) / sizeof(languages[0]); ++i)
            if (code == languages[i]) { languageIndex = i; break; }

        switch (languageIndex)
        {
        case 0: // cs - Credit: JPEXS
            strings.strExtendedOptions = L"Rozšířená nastavení";
            strings.strGodMode = L"Nesmrtelnost";
            strings.hintGodMode = L"\nČervi jsou nesmrtelní, kromě utopení ve vodě.";
            strings.strHighJump = L"Vysoké skoky";
            strings.hintHighJump = L"\nSkákání výše.";
            strings.strSheepHeaven = L"Ovčí nebe";
            strings.hintSheepHeaven = L"\nBedny obsahují ovčí zbraně a doba letu super ovce je prodloužena.";
            strings.strSuperShopperCrates = L"Bedny pro super zákazníka";
            strings.hintSuperShopperCrates = L"\nBedny obsahují tajné zbraně.";
            strings.strExtendedFusesHerds = L"Rozšířená zápalná šňůra / stádo";
            strings.hintExtendedFusesHerds = L"Povolí použití číselných kláves 1-9 místo jen 1-5 pro nastavení zápalné šňůry časovaných zbraní a velikosti stáda zvířat.";
            strings.strUtilitiesDontEndTurn = L"Nástroje neukončí tah";
            strings.hintUtilitiesDontEndTurn = L"Následující zbraně můžeš použít bez ukončení tahu:\n\nautogen, sbíječka, trám, teleport.";
            strings.strWeaponsDontEndTurn = L"Zbraně neukončí tah";
            strings.hintWeaponsDontEndTurn = L"\nPovolí u VŠECH zbraní použití vícekrát během jednoho tahu.";
            strings.strLossOfControlDoesntEndTurn = L"Ztráta kontroly neukončí tah";
            strings.hintLossOfControlDoesntEndTurn = L"Události, které způsobují ztrátu kontroly, budou mít stále ten efekt, ale kontrola může být časem převzata zpět bez ukončení aktuálního tahu.";
            strings.strWormSelectAfterMovement = L"Výběr červa po pohybu";
            strings.hintWormSelectAfterMovement = L"\nMůžeš přepínat na jiné červy po pohybu.";
            strings.strLowGravity = L"Nízká gravitace";
            strings.hintLowGravity = L"\nSníží gravitaci.";
            strings.strPersistentRope = L"Trvalé lano";
            strings.hintPersistentRope = L"Po ukončení svého tahu červi, kteří jsou na ninja laně, zůstanou k němu přivázaní a ti, kteří jsou na bungee lanu, také.";
            strings.strRapidPlay = L"Rychlá hra";
            strings.hintRapidPlay = L"\nOdstraní mnoho průtahů a přestávek pro zrychlení hry.";
            strings.strIndestructibleTerrain = L"Nezničitelný terén";
            strings.hintIndestructibleTerrain = L"Aktivuje nezničitelný terén.\n\nPoznámka: Pečlivě zvaž, na jaké mapě tento cheat použiješ!";
            strings.strInvisibleTerrain = L"Neviditelný terén";
            strings.hintInvisibleTerrain = L"\nPopředí již nebude viditelné.";
            strings.strFastCrates = L"Rychlé bedny";
            strings.hintFastCrates = L"\nBedny padají z nebe mnohem rychleji.";
            strings.strCrateSpy = L"Špión beden";
            strings.hintCrateSpy = L"\nJde vidět, co je v bednách.";
            strings.strCrateLimit = L"Limit beden";
            strings.hintCrateLimit = L"\nHra nevytvoří další bedny, pokud by to překročilo tento limit.";
            strings.strCrateRate = L"Výskyt beden";
            strings.hintCrateRate = L"Určuje, kolik beden smí být potenciálně vytvořeno současně na začátku tahu. S pravděpodobností výsadku nastavenou na 100 % způsobí přesně toto určené množství.";
            strings.strSuicideBomber = L"Sebevražedný atentátník";
            strings.hintSuicideBomber = L"\nZ kamikaze se stane sebevražedný atentátník.";
            strings.strAquaSheep = L"Vodní ovce";
            strings.hintAquaSheep = L"Vylepší každou tvou super ovci na VODNÍ OVCI, která umí plavat stejně dobře jako létat.";
            strings.strInstantMines = L"Instantní miny";
            strings.hintInstantMines = L"\nVšechny miny budou vybuchovat okamžitě, i ty položené hráčem.";
            strings.strHerd = L"Stádo zbraní";
            strings.hintHerd = L"\nSpustí více stejných zbraní.";
            strings.strDisableBackflip = L"Zakázat salto vzad";
            strings.hintDisableBackflip = L"\nSalta vzad nejsou povolená.";
            strings.strDisableUnlockedAim = L"Zakázat odemčené míření";
            strings.hintDisableUnlockedAim = L"Nemůžeš už dále měnit míření během střelby nebo při používání autogenu.";
            break;

        case 1: // de
            strings.strExtendedOptions = L"Erweiterte Spieloptionen";
            strings.strGodMode = L"Unbesiegbarkeit";
            strings.strHighJump = L"Hoher Sprung";
            strings.strSheepHeaven = L"Schafparadies";
            strings.strSuperShopperCrates = L"Kisten mit Geheimwaffen";
            strings.strExtendedFusesHerds = L"Erweiterte Zünder/Herden";
            strings.strUtilitiesDontEndTurn = L"Werkzeuge beenden Zug nicht";
            strings.strWeaponsDontEndTurn = L"Waffennutzung beendet Zug nicht";
            strings.strLossOfControlDoesntEndTurn = L"Kontrollverlust beendet Zug nicht";
            strings.strWormSelectAfterMovement = L"Würmerwahl ist immer aktiv";
            strings.strLowGravity = L"Niedrige Schwer";
            strings.strPersistentRope = L"Fledermaus-Seil";
            strings.strRapidPlay = L"Schnelles Spiel";
            strings.strIndestructibleTerrain = L"Unzerstörbares Land";
            strings.strInvisibleTerrain = L"Unsichtbares Land";
            strings.strFastCrates = L"Schnelle Kisten";
            strings.strCrateSpy = L"Kistenspion";
            strings.strCrateLimit = L"Maximale Kistenzahl auf dem Bildschirm";
            strings.strCrateRate = L"Anzahl der Kistenabwürfe";
            strings.strSuicideBomber = L"Kamikaze -> Kamikaze-Bomber";
            strings.strAquaSheep = L"Aquaschaf";
            strings.strInstantMines = L"Sofort explodierende Minen";
            strings.strHerd = L"Herde";
            strings.strDisableBackflip = L"Rückwärtssalto deaktivieren";
            strings.strDisableUnlockedAim = L"Freies Zielen beim Feuern deaktivieren";
            break;

        case 2: // en
        default: // Unknown or missing language uses English.
            strings.strExtendedOptions = L"Extended Options";
            strings.strGodMode = L"God Mode";
            strings.hintGodMode = L"\nWorms are invincible except for drowning in the water.";
            strings.strHighJump = L"High Jump";
            strings.hintHighJump = L"\nJump higher.";
            strings.strSheepHeaven = L"Sheep Heaven";
            strings.hintSheepHeaven = L"\nCrates contain Sheep weapons and Super Sheep flight time is extended.";
            strings.strSuperShopperCrates = L"Super Shopper Crates";
            strings.hintSuperShopperCrates = L"\nSpawns crates with secret weapons.";
            strings.strExtendedFusesHerds = L"Extended Fuses/Herds";
            strings.hintExtendedFusesHerds = L"Enables the use of numeric keys 1-9 instead of just 1-5 to set timed weapon fuses and animal herd sizes.";
            strings.strUtilitiesDontEndTurn = L"Utilities don't end turn";
            strings.hintUtilitiesDontEndTurn = L"Use these weapons without ending your turn:\n\n" + OptionResourceString(resourceModule, 4934) + L", " +
                OptionResourceString(resourceModule, 4923) + L", " + OptionResourceString(resourceModule, 4922) + L", " + OptionResourceString(resourceModule, 4926) + L".";
            strings.strWeaponsDontEndTurn = L"Weapons don't end turn";
            strings.hintWeaponsDontEndTurn = L"\nAllows ALL weapons to be used multiple times in a single turn.";
            strings.strLossOfControlDoesntEndTurn = L"Loss of control doesn't end turn";
            strings.hintLossOfControlDoesntEndTurn = L"Events that cause loss of control will still have that effect, but control will eventually be regained without ending the current turn.";
            strings.strWormSelectAfterMovement = L"Worm Selection after movement";
            strings.hintWormSelectAfterMovement = L"\nYou can switch to other Worms after moving.";
            strings.strLowGravity = L"Low Gravity";
            strings.hintLowGravity = L"\nLowers the gravity.";
            strings.strPersistentRope = L"Persistent Rope";
            strings.hintPersistentRope = L"After the end of their turns, worms with a Ninja Rope attached will remain attached and those using Bungee will stay on it.";
            strings.strRapidPlay = L"Rapid Play";
            strings.hintRapidPlay = L"\nRemoves lots of delays and pauses to speed up the game.";
            strings.strIndestructibleTerrain = L"Indestructible Terrain";
            strings.hintIndestructibleTerrain = L"Enables indestructible land.\n\nNote: Be careful which terrain you elect to play on!";
            strings.strInvisibleTerrain = L"Invisible Terrain";
            strings.hintInvisibleTerrain = L"\nThe foreground is no longer visible.";
            strings.strFastCrates = L"Fast Crates";
            strings.hintFastCrates = L"\nCrates fall from the sky much faster.";
            strings.strCrateSpy = L"Crate Spy";
            strings.hintCrateSpy = L"\nSee what's inside crates.";
            strings.strCrateLimit = L"Crate Limit";
            strings.hintCrateLimit = L"\nThe game will not spawn crates when doing so would exceed this limit.";
            strings.strCrateRate = L"Crate Rate";
            strings.hintCrateRate = L"Specifies how many crates can potentially spawn simultaneously at the start of the turn. With crate drop probabilities set to 100%, causes the exact amount specified to spawn.";
            strings.strSuicideBomber = L"Suicide Bomber";
            strings.hintSuicideBomber = L"\nKamikaze becomes Suicide Bomber.";
            strings.strAquaSheep = L"Aqua Sheep";
            strings.hintAquaSheep = L"Upgrades any of your Super Sheep into AQUA SHEEP, which can swim as well as fly.";
            strings.strInstantMines = L"Instant Mines";
            strings.hintInstantMines = L"\nAll mines will detonate instantly, even those dropped by the player.";
            strings.strHerd = L"Herd weapon";
            strings.hintHerd = L"\nLaunch multiple of the same weapon.";
            strings.strDisableBackflip = L"Disable Backflip";
            strings.hintDisableBackflip = L"\nBackflips are no longer possible.";
            strings.strDisableUnlockedAim = L"Disable Unlocked Aim";
            strings.hintDisableUnlockedAim = L"\nYou can no longer adjust the aim when firing or using the Blow Torch.";
            break;

        case 3: // es
            strings.strExtendedOptions = L"Opciones de Juego Extendidas";
            strings.strGodMode = L"Invencibilidad";
            strings.strHighJump = L"Salto alto";
            strings.strSheepHeaven = L"Paraíso de las ovejas";
            strings.strSuperShopperCrates = L"Cajas de armas secretas";
            strings.strExtendedFusesHerds = L"Extensión a retardos/manadas";
            strings.strUtilitiesDontEndTurn = L"Las herramientas no terminan el turno";
            strings.strWeaponsDontEndTurn = L"Usar armas no concluye el turno";
            strings.strLossOfControlDoesntEndTurn = L"Perder el control no concluye el turno";
            strings.strWormSelectAfterMovement = L"Nunca cancelar la selección de Worms";
            strings.strLowGravity = L"Baja gravedad";
            strings.strPersistentRope = L"Cuerda y puenting siguen enganchados";
            strings.strRapidPlay = L"Juego rápido";
            strings.strIndestructibleTerrain = L"Terreno indestructible";
            strings.strInvisibleTerrain = L"Terreno invisible";
            strings.strFastCrates = L"Cajas rápidas";
            strings.strCrateSpy = L"Espía de cajas";
            strings.strCrateLimit = L"Máximo número de cajas en el mapa a la vez";
            strings.strCrateRate = L"Frecuencia de cajas";
            strings.strSuicideBomber = L"Kamikaze -> Bomba suicida";
            strings.strAquaSheep = L"Oveja acuática";
            strings.strInstantMines = L"Minas instantáneas";
            strings.strHerd = L"Manada";
            strings.strDisableBackflip = L"Desactivar salto hacia atrás";
            strings.strDisableUnlockedAim = L"Desactivar apuntado libre al disparar";
            break;

        case 4: // es-419
            strings.strExtendedOptions = L"Opciones extendidas";
            strings.strGodMode = L"Modo Dios";
            strings.strHighJump = L"Salto alto";
            strings.strSheepHeaven = L"Paraíso de las ovejas";
            strings.strSuperShopperCrates = L"Cajas de armas secretas";
            strings.strExtendedFusesHerds = L"Mechas/rebaños ampliados";
            strings.strUtilitiesDontEndTurn = L"Las herramientas no terminan el turno";
            strings.strWeaponsDontEndTurn = L"Las armas no terminan el turno";
            strings.strLossOfControlDoesntEndTurn = L"Perder el control no termina el turno";
            strings.strWormSelectAfterMovement = L"Seleccionar gusano después de moverse";
            strings.strLowGravity = L"Gravedad baja";
            strings.strPersistentRope = L"Cuerda y bungee siguen sujetos";
            strings.strRapidPlay = L"Juego rápido";
            strings.strIndestructibleTerrain = L"Terreno indestructible";
            strings.strInvisibleTerrain = L"Terreno invisible";
            strings.strFastCrates = L"Cajas rápidas";
            strings.strCrateSpy = L"Espía de cajas";
            strings.strCrateLimit = L"Límite de cajas";
            strings.strCrateRate = L"Frecuencia de cajas";
            strings.strSuicideBomber = L"Camicace -> Atacante suicida";
            strings.strAquaSheep = L"Oveja acuática";
            strings.strInstantMines = L"Minas instantáneas";
            strings.strHerd = L"Arma de rebaño";
            strings.strDisableBackflip = L"Desactivar salto hacia atrás";
            strings.strDisableUnlockedAim = L"Desactivar mira libre al disparar";
            break;

        case 5: // fr
            strings.strExtendedOptions = L"Options de jeu étendues";
            strings.strGodMode = L"Invincibilité";
            strings.strHighJump = L"Saut en hauteur";
            strings.strSheepHeaven = L"Paradis des moutons";
            strings.strSuperShopperCrates = L"Caisses d'armes secrètes";
            strings.strExtendedFusesHerds = L"Détonateurs et troupeaux étendus";
            strings.strUtilitiesDontEndTurn = L"Les outils ne terminent pas le tour";
            strings.strWeaponsDontEndTurn = L"Utiliser une arme ne met pas fin au tour";
            strings.strLossOfControlDoesntEndTurn = L"Perdre le contrôle ne met pas fin de tour";
            strings.strWormSelectAfterMovement = L"Sélection de ver permanente";
            strings.strLowGravity = L"Faible pesanteur";
            strings.strPersistentRope = L"Corde et élastique restent attachés";
            strings.strRapidPlay = L"Partie rapide";
            strings.strIndestructibleTerrain = L"Terrain indestructible";
            strings.strInvisibleTerrain = L"Terrain invisible";
            strings.strFastCrates = L"Caisses rapides";
            strings.strCrateSpy = L"Contenu des caisses";
            strings.strCrateLimit = L"Nombre maximal de caisses simultanées";
            strings.strCrateRate = L"Taux de caisses";
            strings.strSuicideBomber = L"Kamikaze -> Bombardier kamikaze";
            strings.strAquaSheep = L"Mouton aquatique";
            strings.strInstantMines = L"Mines instantanées";
            strings.strHerd = L"Troupeau";
            strings.strDisableBackflip = L"Désactiver le salto arrière";
            strings.strDisableUnlockedAim = L"Désactiver la visée libre pendant le tir";
            break;

        case 6: // is
            strings.strExtendedOptions = L"";
            strings.strGodMode = L"";
            strings.strHighJump = L"";
            strings.strSheepHeaven = L"";
            strings.strSuperShopperCrates = L"";
            strings.strExtendedFusesHerds = L"";
            strings.strUtilitiesDontEndTurn = L"";
            strings.strWeaponsDontEndTurn = L"";
            strings.strLossOfControlDoesntEndTurn = L"";
            strings.strWormSelectAfterMovement = L"";
            strings.strLowGravity = L"";
            strings.strPersistentRope = L"";
            strings.strRapidPlay = L"";
            strings.strIndestructibleTerrain = L"";
            strings.strInvisibleTerrain = L"";
            strings.strFastCrates = L"";
            strings.strCrateSpy = L"";
            strings.strCrateLimit = L"";
            strings.strCrateRate = L"";
            strings.strSuicideBomber = L"";
            strings.strAquaSheep = L"";
            strings.strInstantMines = L"";
            strings.strHerd = L"";
            strings.strDisableBackflip = L"";
            strings.strDisableUnlockedAim = L"";
            break;

        case 7: // it
            strings.strExtendedOptions = L"Opzioni estese";
            strings.strGodMode = L"Invincibilità";
            strings.strHighJump = L"Salto alto";
            strings.strSheepHeaven = L"Paradiso delle pecore";
            strings.strSuperShopperCrates = L"Casse di armi segrete";
            strings.strExtendedFusesHerds = L"Micce/greggi estesi";
            strings.strUtilitiesDontEndTurn = L"Gli strumenti non terminano il turno";
            strings.strWeaponsDontEndTurn = L"Le armi non terminano il turno";
            strings.strLossOfControlDoesntEndTurn = L"La perdita di controllo non termina il turno";
            strings.strWormSelectAfterMovement = L"Selezione del verme dopo il movimento";
            strings.strLowGravity = L"Bassa gravità";
            strings.strPersistentRope = L"Corda persistente";
            strings.strRapidPlay = L"Gioco rapido";
            strings.strIndestructibleTerrain = L"Terreno indistruttibile";
            strings.strInvisibleTerrain = L"Terreno invisibile";
            strings.strFastCrates = L"Casse veloci";
            strings.strCrateSpy = L"Cassa spia";
            strings.strCrateLimit = L"Limite di casse";
            strings.strCrateRate = L"Frequenza delle casse";
            strings.strSuicideBomber = L"Kamikaze -> Suicidio tossico";
            strings.strAquaSheep = L"Pecora acquatica";
            strings.strInstantMines = L"Mine istantanee";
            strings.strHerd = L"Mandria";
            strings.strDisableBackflip = L"Disabilita il salto all'indietro";
            strings.strDisableUnlockedAim = L"Disabilita la mira libera durante il tiro";
            break;

        case 8: // nl
            strings.strExtendedOptions = L"Uitgebreide opties";
            strings.strGodMode = L"Onoverwinnelijk";
            strings.strHighJump = L"Hoge sprong";
            strings.strSheepHeaven = L"Schapenparadijs";
            strings.strSuperShopperCrates = L"Kratten met geheime wapens";
            strings.strExtendedFusesHerds = L"Uitgebreide lonten/kuddes";
            strings.strUtilitiesDontEndTurn = L"Hulpmiddelen beëindigen beurt niet";
            strings.strWeaponsDontEndTurn = L"Wapens beëindigen beurt niet";
            strings.strLossOfControlDoesntEndTurn = L"Controleverlies beëindigt beurt niet";
            strings.strWormSelectAfterMovement = L"Worm kiezen na verplaatsing";
            strings.strLowGravity = L"Minder zwaarte";
            strings.strPersistentRope = L"Touw en bungee blijven vastzitten";
            strings.strRapidPlay = L"Snel spelen";
            strings.strIndestructibleTerrain = L"Onverwoestbaar terrein";
            strings.strInvisibleTerrain = L"Onzichtbaar terrein";
            strings.strFastCrates = L"Snelle kratten";
            strings.strCrateSpy = L"Krattenspion";
            strings.strCrateLimit = L"Krattenlimiet";
            strings.strCrateRate = L"Krattenfrequentie";
            strings.strSuicideBomber = L"Kamikaze -> Zelfmoordaanval";
            strings.strAquaSheep = L"Waterschaap";
            strings.strInstantMines = L"Onmiddellijk ontploffende mijnen";
            strings.strHerd = L"Kudde";
            strings.strDisableBackflip = L"Achterwaartse salto uitschakelen";
            strings.strDisableUnlockedAim = L"Vrij richten tijdens vuren uitschakelen";
            break;

        case 9: // pl
            strings.strExtendedOptions = L"";
            strings.strGodMode = L"";
            strings.hintGodMode = L"";
            strings.strHighJump = L"";
            strings.hintHighJump = L"";
            strings.strSheepHeaven = L"";
            strings.hintSheepHeaven = L"";
            strings.strSuperShopperCrates = L"";
            strings.hintSuperShopperCrates = L"";
            strings.strExtendedFusesHerds = L"";
            strings.hintExtendedFusesHerds = L"";
            strings.strUtilitiesDontEndTurn = L"";
            strings.hintUtilitiesDontEndTurn = L"";
            strings.strWeaponsDontEndTurn = L"";
            strings.hintWeaponsDontEndTurn = L"";
            strings.strLossOfControlDoesntEndTurn = L"";
            strings.hintLossOfControlDoesntEndTurn = L"";
            strings.strWormSelectAfterMovement = L"";
            strings.hintWormSelectAfterMovement = L"";
            strings.strLowGravity = L"";
            strings.hintLowGravity = L"";
            strings.strPersistentRope = L"";
            strings.hintPersistentRope = L"";
            strings.strRapidPlay = L"";
            strings.hintRapidPlay = L"";
            strings.strIndestructibleTerrain = L"";
            strings.hintIndestructibleTerrain = L"";
            strings.strInvisibleTerrain = L"";
            strings.hintInvisibleTerrain = L"";
            strings.strFastCrates = L"";
            strings.hintFastCrates = L"";
            strings.strCrateSpy = L"";
            strings.hintCrateSpy = L"";
            strings.strCrateLimit = L"";
            strings.hintCrateLimit = L"";
            strings.strCrateRate = L"";
            strings.hintCrateRate = L"";
            strings.strSuicideBomber = L"";
            strings.hintSuicideBomber = L"";
            strings.strAquaSheep = L"";
            strings.hintAquaSheep = L"";
            strings.strInstantMines = L"";
            strings.hintInstantMines = L"";
            strings.strHerd = L"";
            strings.hintHerd = L"";
            strings.strDisableBackflip = L"";
            strings.hintDisableBackflip = L"";
            strings.strDisableUnlockedAim = L"";
            strings.hintDisableUnlockedAim = L"";
            break;

        case 10: // pt
            strings.strExtendedOptions = L"Opções de jogo alargadas";
            strings.strGodMode = L"Invisibilidade";
            strings.hintGodMode = L"As minhocas são invencíveis, exceto se se afogarem na água.";
            strings.strHighJump = L"";
            strings.hintHighJump = L"";
            strings.strSheepHeaven = L"";
            strings.hintSheepHeaven = L"";
            strings.strSuperShopperCrates = L"";
            strings.hintSuperShopperCrates = L"";
            strings.strExtendedFusesHerds = L"Fusíveis/manadas alargadas";
            strings.hintExtendedFusesHerds = L"Permite o uso das teclas numéricas 0-9 em vez de apenas 1-5 para definir os fusíveis das armas temporizadas e o tamanho das manadas de animais. A tecla 0 define 0 segundos para as armas temporizadas e 10 animais para as manadas.";
            strings.strUtilitiesDontEndTurn = L"";
            strings.hintUtilitiesDontEndTurn = L"";
            strings.strWeaponsDontEndTurn = L"A utilização da arma não termina o turno";
            strings.hintWeaponsDontEndTurn = L"Permite que as armas sejam usadas várias vezes num único turno.";
            strings.strLossOfControlDoesntEndTurn = L"A perda de controlo não acaba o turno";
            strings.hintLossOfControlDoesntEndTurn = L"Quando ativado, os eventos que causam perda de controlo continuam a ter esse efeito, mas o controlo acaba por ser recuperado sem terminar o turno atual.";
            strings.strWormSelectAfterMovement = L"A Seleção de Minhocas nunca é cancelada";
            strings.hintWormSelectAfterMovement = L"A tecla Tab pode ser sempre usada durante um turno para mudar para outra Minhoca.";
            strings.strLowGravity = L"Baixa Gravidade";
            strings.hintLowGravity = L"";
            strings.strPersistentRope = L"Corda Morcego";
            strings.hintPersistentRope = L"Após o fim dos teus turnos, as minhocas com uma Corda Ninja engatada permanecerão ligadas, as que usarem Bungee permanecerão nela e as que usarem o Jet Pack irão mantê-lo equipado.";
            strings.strRapidPlay = L"";
            strings.hintRapidPlay = L"";
            strings.strIndestructibleTerrain = L"";
            strings.hintIndestructibleTerrain = L"";
            strings.strInvisibleTerrain = L"";
            strings.hintInvisibleTerrain = L"";
            strings.strFastCrates = L"";
            strings.hintFastCrates = L"";
            strings.strCrateSpy = L"Espiar Caixas";
            strings.hintCrateSpy = L"";
            strings.strCrateLimit = L"Contagem máxima de caixas no mapa de uma só vez";
            strings.hintCrateLimit = L"O jogo não vai gerar caixas se ultrapassar este limite.";
            strings.strCrateRate = L"Frequência das Caixas";
            strings.hintCrateRate = L"Especifica quantas caixas podem potencialmente aparecer simultaneamente no início do turno, até ao máximo definido por \"Contagem máxima de caixas no mapa no início\". Com as probabilidades de queda de caixas definidas para 100%, faz aparecer a quantidade exata especificada.";
            strings.strSuicideBomber = L"Bombista Suicida";
            strings.hintSuicideBomber = L"Kamikaze -> Bombista Suicida";
            strings.strAquaSheep = L"Ovelha Aquática";
            strings.hintAquaSheep = L"Transforma qualquer uma das tuas Super Ovelhas em OVELHAS AQUÁTICAS, que podem nadar e voar.";
            strings.strInstantMines = L"";
            strings.hintInstantMines = L"";
            strings.strHerd = L"Manada";
            strings.hintHerd = L"";
            strings.strDisableBackflip = L"";
            strings.hintDisableBackflip = L"";
            strings.strDisableUnlockedAim = L"";
            strings.hintDisableUnlockedAim = L"";
            break;

        case 11: // pt-br
            strings.strExtendedOptions = L"Opções de Jogo Estendidas";
            strings.strGodMode = L"Invencibilidade";
            strings.hintGodMode = L"As minhocas são invencíveis, mas podem morrer afogadas.";
            strings.strHighJump = L"";
            strings.hintHighJump = L"";
            strings.strSheepHeaven = L"";
            strings.hintSheepHeaven = L"";
            strings.strSuperShopperCrates = L"";
            strings.hintSuperShopperCrates = L"";
            strings.strExtendedFusesHerds = L"Detonadores/rebanhos estendidos";
            strings.hintExtendedFusesHerds = L"Permite o uso das teclas numéricas de 0 a 9 em vez de apenas de 1 a 5 para definir o tempo de detonação de armas cronometrados e a quantidade de rebanho de animais. A tecla 0 define 0 segundos para armas cronometradas e 10 animais para rebanhos.";
            strings.strUtilitiesDontEndTurn = L"";
            strings.hintUtilitiesDontEndTurn = L"";
            strings.strWeaponsDontEndTurn = L"Uso de armas não finalizam o turno";
            strings.hintWeaponsDontEndTurn = L"Permite que armas sejam usadas várias vezes em um único turno.";
            strings.strLossOfControlDoesntEndTurn = L"Perdas de controle não finalizam o turno";
            strings.hintLossOfControlDoesntEndTurn = L"Quando ativado, os comportamentos que causam perda de controle ainda terão esse efeito, mas o controle eventualmente será recuperado sem terminar o turno atual.";
            strings.strWormSelectAfterMovement = L"Seleção de Minhoca nunca é cancelada";
            strings.hintWormSelectAfterMovement = L"Determina se a tecla Tab pode ser sempre usada durante um turno para mudar para outra Minhoca.";
            strings.strLowGravity = L"Baixa Gravidade";
            strings.hintLowGravity = L"";
            strings.strPersistentRope = L"Modo Morcego";
            strings.hintPersistentRope = L"Após o final de seus turnos, minhocas penduradas por uma Corda Ninja ou Bungee Jump permanecerão penduradas, o mesmo acontece para a Mochila a Jato que permanecerá equipada.";
            strings.strRapidPlay = L"";
            strings.hintRapidPlay = L"";
            strings.strIndestructibleTerrain = L"";
            strings.hintIndestructibleTerrain = L"";
            strings.strInvisibleTerrain = L"";
            strings.hintInvisibleTerrain = L"";
            strings.strFastCrates = L"";
            strings.hintFastCrates = L"";
            strings.strCrateSpy = L"Espião de Caixas";
            strings.hintCrateSpy = L"";
            strings.strCrateLimit = L"Contagem máxima de caixas no mapa de uma só vez";
            strings.hintCrateLimit = L"O jogo não gerará mais caixas quando exceder o limite estabelecido.";
            strings.strCrateRate = L"Taxa de caixas";
            strings.hintCrateRate = L"Especifica quantas caixas podem gerar simultaneamente no início do turno, até o máximo definido por \"Contagem máxima de caixas no mapa de uma só vez\". Com probabilidades de queda de caixa configuradas como 100%, faz com que a quantidade exata especificada seja gerada.";
            strings.strSuicideBomber = L"Bomba Suicida";
            strings.hintSuicideBomber = L"Kamikaze -> Bomba Suicida";
            strings.strAquaSheep = L"Aqua Carneiro";
            strings.hintAquaSheep = L"Aprimora qualquer um dos seus super carneiros em CARNEIRO AQUÁTICO, que além de voar também podem nadar.";
            strings.strInstantMines = L"";
            strings.hintInstantMines = L"";
            strings.strHerd = L"Rebanho/manada";
            strings.hintHerd = L"";
            strings.strDisableBackflip = L"";
            strings.hintDisableBackflip = L"";
            strings.strDisableUnlockedAim = L"";
            strings.hintDisableUnlockedAim = L"";
            break;

        case 12: // ru
            strings.strExtendedOptions = L"Расширенные настройки игры";
            strings.strGodMode = L"Неуязвимость";
            strings.strHighJump = L"Высокий прыжок";
            strings.strSheepHeaven = L"Овечий рай";
            strings.strSuperShopperCrates = L"Ящики с секретным оружием";
            strings.strExtendedFusesHerds = L"расширенные задержки гранат и стада животных";
            strings.strUtilitiesDontEndTurn = L"Инструменты не завершают ход";
            strings.strWeaponsDontEndTurn = L"Выстрелы не прекращают ход";
            strings.strLossOfControlDoesntEndTurn = L"Потеря контроля не прекращает ход";
            strings.strWormSelectAfterMovement = L"Выбор червя не отменяется";
            strings.strLowGravity = L"Низк. гравит";
            strings.strPersistentRope = L"Верёвка и банджи остаются закреплёнными";
            strings.strRapidPlay = L"Быстрая игра";
            strings.strIndestructibleTerrain = L"Неразрушимый ландшафт";
            strings.strInvisibleTerrain = L"Невидимый ландшафт";
            strings.strFastCrates = L"Быстрые ящики";
            strings.strCrateSpy = L"Шпион ящиков";
            strings.strCrateLimit = L"Максимальное число ящиков на карте";
            strings.strCrateRate = L"коэффициент выпадения ящиков";
            strings.strSuicideBomber = L"Камикадзе -> Суицид-бомба";
            strings.strAquaSheep = L"Аква-овца";
            strings.strInstantMines = L"Мгновенные мины";
            strings.strHerd = L"Стадо";
            strings.strDisableBackflip = L"Отключить сальто назад";
            strings.strDisableUnlockedAim = L"Отключить свободное прицеливание при стрельбе";
            break;

        case 13: // sv
            strings.strExtendedOptions = L"Utökade Spelinställningar";
            strings.strGodMode = L"Oövervinnelighet";
            strings.strHighJump = L"Höga hopp";
            strings.strSheepHeaven = L"Fårparadis";
            strings.strSuperShopperCrates = L"Lådor med hemliga vapen";
            strings.strExtendedFusesHerds = L"Utökade stubiner/flockar";
            strings.strUtilitiesDontEndTurn = L"Verktyg avslutar inte turen";
            strings.strWeaponsDontEndTurn = L"Vapenanvändning avslutar ej runda";
            strings.strLossOfControlDoesntEndTurn = L"Kontrollförlust avslutar ej runda";
            strings.strWormSelectAfterMovement = L"Maskval avbryts aldrig";
            strings.strLowGravity = L"Låg Gravitation";
            strings.strPersistentRope = L"Rep och bungy förblir fästa";
            strings.strRapidPlay = L"Snabbt spel";
            strings.strIndestructibleTerrain = L"Oförstörbar terräng";
            strings.strInvisibleTerrain = L"Osynlig terräng";
            strings.strFastCrates = L"Snabba lådor";
            strings.strCrateSpy = L"Lådspion";
            strings.strCrateLimit = L"Maximalt antal lådor på kartan samtidigt";
            strings.strCrateRate = L"Lådfrekvens";
            strings.strSuicideBomber = L"Kamikaze -> Självmordsbomb";
            strings.strAquaSheep = L"Vattenfår";
            strings.strInstantMines = L"Omedelbara minor";
            strings.strHerd = L"Hjord";
            strings.strDisableBackflip = L"Inaktivera bakåtvolt";
            strings.strDisableUnlockedAim = L"Inaktivera fritt sikte vid skott";
            break;

        case 14: // zh-Hans
            strings.strExtendedOptions = L"";
            strings.strGodMode = L"";
            strings.hintGodMode = L"";
            strings.strHighJump = L"";
            strings.hintHighJump = L"";
            strings.strSheepHeaven = L"";
            strings.hintSheepHeaven = L"";
            strings.strSuperShopperCrates = L"";
            strings.hintSuperShopperCrates = L"";
            strings.strExtendedFusesHerds = L"";
            strings.hintExtendedFusesHerds = L"";
            strings.strUtilitiesDontEndTurn = L"";
            strings.hintUtilitiesDontEndTurn = L"";
            strings.strWeaponsDontEndTurn = L"";
            strings.hintWeaponsDontEndTurn = L"";
            strings.strLossOfControlDoesntEndTurn = L"";
            strings.hintLossOfControlDoesntEndTurn = L"";
            strings.strWormSelectAfterMovement = L"";
            strings.hintWormSelectAfterMovement = L"";
            strings.strLowGravity = L"";
            strings.hintLowGravity = L"";
            strings.strPersistentRope = L"";
            strings.hintPersistentRope = L"";
            strings.strRapidPlay = L"";
            strings.hintRapidPlay = L"";
            strings.strIndestructibleTerrain = L"";
            strings.hintIndestructibleTerrain = L"";
            strings.strInvisibleTerrain = L"";
            strings.hintInvisibleTerrain = L"";
            strings.strFastCrates = L"";
            strings.hintFastCrates = L"";
            strings.strCrateSpy = L"";
            strings.hintCrateSpy = L"";
            strings.strCrateLimit = L"";
            strings.hintCrateLimit = L"";
            strings.strCrateRate = L"";
            strings.hintCrateRate = L"";
            strings.strSuicideBomber = L"";
            strings.hintSuicideBomber = L"";
            strings.strAquaSheep = L"";
            strings.hintAquaSheep = L"";
            strings.strInstantMines = L"";
            strings.hintInstantMines = L"";
            strings.strHerd = L"";
            strings.hintHerd = L"";
            strings.strDisableBackflip = L"";
            strings.hintDisableBackflip = L"";
            strings.strDisableUnlockedAim = L"";
            strings.hintDisableUnlockedAim = L"";
            break;

        }
        strings.strHerdDynamite = strings.strHerd + L": " + OptionResourceString(resourceModule, 4915);
        strings.strHerdMine = strings.strHerd + L": " + OptionResourceString(resourceModule, 4916);
        strings.strHerdMingVase = strings.strHerd + L": " + OptionResourceString(resourceModule, 4917);
        strings.strHerdSheep = strings.strHerd + L": " + OptionResourceString(resourceModule, 4930);
        return strings;
    }
}
