#pragma once
#include <Windows.h>
#include <cstddef>
#include <string>

namespace ExtendedOptions
{
    struct OptionStrings
    {
        std::wstring strExtendedOptions;
        std::wstring strGodMode;
        std::wstring hintGodMode;
        std::wstring strHighJump;
        std::wstring hintHighJump;
        std::wstring strSheepHeaven;
        std::wstring hintSheepHeaven;
        std::wstring strSuperShopperCrates;
        std::wstring hintSuperShopperCrates;
        std::wstring strExtendedFusesHerds;
        std::wstring hintExtendedFusesHerds;
        std::wstring strUtilitiesDontEndTurn;
        std::wstring hintUtilitiesDontEndTurn;
        std::wstring strWeaponsDontEndTurn;
        std::wstring hintWeaponsDontEndTurn;
        std::wstring strLossOfControlDoesntEndTurn;
        std::wstring hintLossOfControlDoesntEndTurn;
        std::wstring strWormSelectAfterMovement;
        std::wstring hintWormSelectAfterMovement;
        std::wstring strLowGravity;
        std::wstring hintLowGravity;
        std::wstring strPersistentRope;
        std::wstring hintPersistentRope;
        std::wstring strRapidPlay;
        std::wstring hintRapidPlay;
        std::wstring strIndestructibleTerrain;
        std::wstring hintIndestructibleTerrain;
        std::wstring strInvisibleTerrain;
        std::wstring hintInvisibleTerrain;
        std::wstring strFastCrates;
        std::wstring hintFastCrates;
        std::wstring strCrateSpy;
        std::wstring hintCrateSpy;
        std::wstring strCrateLimit;
        std::wstring hintCrateLimit;
        std::wstring strCrateRate;
        std::wstring hintCrateRate;
        std::wstring strSuicideBomber;
        std::wstring hintSuicideBomber;
        std::wstring strAquaSheep;
        std::wstring hintAquaSheep;
        std::wstring strInstantMines;
        std::wstring hintInstantMines;
        std::wstring strHerd;
        std::wstring hintHerd;
        // All four derived herd captions use hintHerd.
        std::wstring strHerdDynamite;
        std::wstring strHerdMine;
        std::wstring strHerdMingVase;
        std::wstring strHerdSheep;
        std::wstring strDisableBackflip;
        std::wstring hintDisableBackflip;
        std::wstring strDisableUnlockedAim;
        std::wstring hintDisableUnlockedAim;
    };

    inline std::wstring OptionResourceString(HMODULE resourceModule, UINT stringId)
    {
        wchar_t text[256]{};
        LoadStringW(resourceModule, stringId, text, 256);
        return text;
    }

    // Fill each language case below. Blank translations intentionally remain blank.
    inline OptionStrings MakeOptionStrings(const std::string& language, HMODULE resourceModule)
    {
        OptionStrings strings{};
        const char* const languages[] = {
            "cs", "de", "en", "es", "es-419", "fr", "is", "it", "nl", "pl", "pt", "pt-br", "ru", "sv", "zh-Hans"
        };
        std::string code = language;
        if (code.compare(0, 3, "\xEF\xBB\xBF") == 0) code.erase(0, 3);
        const auto first = code.find_first_not_of(" \t\r\n");
        code = first == std::string::npos ? std::string{} :
            code.substr(first, code.find_last_not_of(" \t\r\n") - first + 1);
        size_t languageIndex = 2; // English fallback.
        for (size_t i = 0; i < sizeof(languages) / sizeof(languages[0]); ++i)
            if (code == languages[i]) { languageIndex = i; break; }

        switch (languageIndex)
        {
        case 0: // cs - Credit: JPEXS
            strings.strExtendedOptions = L"Rozšířená nastavení";
            strings.strGodMode = L"Nesmrtelnost";
            strings.hintGodMode = L"\nČervi jsou nesmrtelní, kromě utopení ve vodě.";
            strings.strHighJump = L"Vysoké skoky";
            strings.hintHighJump = L"\nSkákání výše.";
            strings.strSheepHeaven = L"Ovčí nebe";
            strings.hintSheepHeaven = L"\nBedny obsahují ovčí zbraně a doba letu super ovce je prodloužena.";
            strings.strSuperShopperCrates = L"Bedny pro super zákazníka";
            strings.hintSuperShopperCrates = L"\nBedny obsahují tajné zbraně.";
            strings.strExtendedFusesHerds = L"Rozšířená zápalná šňůra / stádo";
            strings.hintExtendedFusesHerds = L"Povolí použití číselných kláves 1-9 místo jen 1-5 pro nastavení zápalné šňůry časovaných zbraní a velikosti stáda zvířat.";
            strings.strUtilitiesDontEndTurn = L"Nástroje neukončí tah";
            strings.hintUtilitiesDontEndTurn = L"Následující zbraně můžeš použít bez ukončení tahu:\n\nautogen, sbíječka, trám, teleport.";
            strings.strWeaponsDontEndTurn = L"Zbraně neukončí tah";
            strings.hintWeaponsDontEndTurn = L"\nPovolí u VŠECH zbraní použití vícekrát během jednoho tahu.";
            strings.strLossOfControlDoesntEndTurn = L"Ztráta kontroly neukončí tah";
            strings.hintLossOfControlDoesntEndTurn = L"Události, které způsobují ztrátu kontroly, budou mít stále ten efekt, ale kontrola může být časem převzata zpět bez ukončení aktuálního tahu.";
            strings.strWormSelectAfterMovement = L"Výběr červa po pohybu";
            strings.hintWormSelectAfterMovement = L"\nMůžeš přepínat na jiné červy po pohybu.";
            strings.strLowGravity = L"Nízká gravitace";
            strings.hintLowGravity = L"\nSníží gravitaci.";
            strings.strPersistentRope = L"Trvalé lano";
            strings.hintPersistentRope = L"Po ukončení svého tahu červi, kteří jsou na ninja laně, zůstanou k němu přivázaní a ti, kteří jsou na bungee lanu, také.";
            strings.strRapidPlay = L"Rychlá hra";
            strings.hintRapidPlay = L"\nOdstraní mnoho průtahů a přestávek pro zrychlení hry.";
            strings.strIndestructibleTerrain = L"Nezničitelný terén";
            strings.hintIndestructibleTerrain = L"Aktivuje nezničitelný terén.\n\nPoznámka: Pečlivě zvaž, na jaké mapě tento cheat použiješ!";
            strings.strInvisibleTerrain = L"Neviditelný terén";
            strings.hintInvisibleTerrain = L"\nPopředí již nebude viditelné.";
            strings.strFastCrates = L"Rychlé bedny";
            strings.hintFastCrates = L"\nBedny padají z nebe mnohem rychleji.";
            strings.strCrateSpy = L"Špión beden";
            strings.hintCrateSpy = L"\nJde vidět, co je v bednách.";
            strings.strCrateLimit = L"Limit beden";
            strings.hintCrateLimit = L"\nHra nevytvoří další bedny, pokud by to překročilo tento limit.";
            strings.strCrateRate = L"Výskyt beden";
            strings.hintCrateRate = L"Určuje, kolik beden smí být potenciálně vytvořeno současně na začátku tahu. S pravděpodobností výsadku nastavenou na 100 % způsobí přesně toto určené množství.";
            strings.strSuicideBomber = L"Sebevražedný atentátník";
            strings.hintSuicideBomber = L"\nZ kamikaze se stane sebevražedný atentátník.";
            strings.strAquaSheep = L"Vodní ovce";
            strings.hintAquaSheep = L"Vylepší každou tvou super ovci na VODNÍ OVCI, která umí plavat stejně dobře jako létat.";
            strings.strInstantMines = L"Instantní miny";
            strings.hintInstantMines = L"\nVšechny miny budou vybuchovat okamžitě, i ty položené hráčem.";
            strings.strHerd = L"Stádo zbraní";
            strings.hintHerd = L"\nSpustí více stejných zbraní.";
            strings.strDisableBackflip = L"Zakázat salto vzad";
            strings.hintDisableBackflip = L"\nSalta vzad nejsou povolená.";
            strings.strDisableUnlockedAim = L"Zakázat odemčené míření";
            strings.hintDisableUnlockedAim = L"Nemůžeš už dále měnit míření během střelby nebo při používání autogenu.";
            break;

        case 1: // de
            strings.strExtendedOptions = L"Erweiterte Spieloptionen";
            strings.strGodMode = L"Unbesiegbarkeit";
            strings.strHighJump = L"Hoher Sprung";
            strings.strSheepHeaven = L"Schafparadies";
            strings.strSuperShopperCrates = L"Kisten mit Geheimwaffen";
            strings.strExtendedFusesHerds = L"Erweiterte Zünder/Herden";
            strings.strUtilitiesDontEndTurn = L"Werkzeuge beenden Zug nicht";
            strings.strWeaponsDontEndTurn = L"Waffennutzung beendet Zug nicht";
            strings.strLossOfControlDoesntEndTurn = L"Kontrollverlust beendet Zug nicht";
            strings.strWormSelectAfterMovement = L"Würmerwahl ist immer aktiv";
            strings.strLowGravity = L"Niedrige Schwer";
            strings.strPersistentRope = L"Fledermaus-Seil";
            strings.strRapidPlay = L"Schnelles Spiel";
            strings.strIndestructibleTerrain = L"Unzerstörbares Land";
            strings.strInvisibleTerrain = L"Unsichtbares Land";
            strings.strFastCrates = L"Schnelle Kisten";
            strings.strCrateSpy = L"Kistenspion";
            strings.strCrateLimit = L"Maximale Kistenzahl auf dem Bildschirm";
            strings.strCrateRate = L"Anzahl der Kistenabwürfe";
            strings.strSuicideBomber = L"Kamikaze -> Kamikaze-Bomber";
            strings.strAquaSheep = L"Aquaschaf";
            strings.strInstantMines = L"Sofort explodierende Minen";
            strings.strHerd = L"Herde";
            strings.strDisableBackflip = L"Rückwärtssalto deaktivieren";
            strings.strDisableUnlockedAim = L"Freies Zielen beim Feuern deaktivieren";
            break;

        case 2: // en
        default: // Unknown or missing language uses English.
            strings.strExtendedOptions = L"Extended Options";
            strings.strGodMode = L"God Mode";
            strings.hintGodMode = L"\nWorms are invincible except for drowning in the water.";
            strings.strHighJump = L"High Jump";
            strings.hintHighJump = L"\nJump higher.";
            strings.strSheepHeaven = L"Sheep Heaven";
            strings.hintSheepHeaven = L"\nCrates contain Sheep weapons and Super Sheep flight time is extended.";
            strings.strSuperShopperCrates = L"Super Shopper Crates";
            strings.hintSuperShopperCrates = L"\nSpawns crates with secret weapons.";
            strings.strExtendedFusesHerds = L"Extended Fuses/Herds";
            strings.hintExtendedFusesHerds = L"Enables the use of numeric keys 1-9 instead of just 1-5 to set timed weapon fuses and animal herd sizes.";
            strings.strUtilitiesDontEndTurn = L"Utilities don't end turn";
            strings.hintUtilitiesDontEndTurn = L"Use these weapons without ending your turn:\n\nBlow Torch, Drill, Girder, Teleport.";
            strings.strWeaponsDontEndTurn = L"Weapons don't end turn";
            strings.hintWeaponsDontEndTurn = L"\nAllows ALL weapons to be used multiple times in a single turn.";
            strings.strLossOfControlDoesntEndTurn = L"Loss of control doesn't end turn";
            strings.hintLossOfControlDoesntEndTurn = L"Events that cause loss of control will still have that effect, but control will eventually be regained without ending the current turn.";
            strings.strWormSelectAfterMovement = L"Worm selection after movement";
            strings.hintWormSelectAfterMovement = L"\nYou can switch to other Worms after moving.";
            strings.strLowGravity = L"Low Gravity";
            strings.hintLowGravity = L"\nLowers the gravity.";
            strings.strPersistentRope = L"Persistent Rope";
            strings.hintPersistentRope = L"After the end of their turns, worms with a Ninja Rope attached will remain attached and those using Bungee will stay on it.";
            strings.strRapidPlay = L"Rapid Play";
            strings.hintRapidPlay = L"\nRemoves lots of delays and pauses to speed up the game.";
            strings.strIndestructibleTerrain = L"Indestructible Terrain";
            strings.hintIndestructibleTerrain = L"Enables indestructible land.\n\nNote: Be careful which terrain you elect to play on!";
            strings.strInvisibleTerrain = L"Invisible Terrain";
            strings.hintInvisibleTerrain = L"\nThe foreground is no longer visible.";
            strings.strFastCrates = L"Fast Crates";
            strings.hintFastCrates = L"\nCrates fall from the sky much faster.";
            strings.strCrateSpy = L"Crate Spy";
            strings.hintCrateSpy = L"\nSee what's inside crates.";
            strings.strCrateLimit = L"Crate Limit";
            strings.hintCrateLimit = L"\nThe game will not spawn crates when doing so would exceed this limit.";
            strings.strCrateRate = L"Crate Rate";
            strings.hintCrateRate = L"Specifies how many crates can potentially spawn simultaneously at the start of the turn. With crate drop probabilities set to 100%, causes the exact amount specified to spawn.";
            strings.strSuicideBomber = L"Suicide Bomber";
            strings.hintSuicideBomber = L"\nKamikaze becomes Suicide Bomber.";
            strings.strAquaSheep = L"Aqua Sheep";
            strings.hintAquaSheep = L"Upgrades any of your Super Sheep into AQUA SHEEP, which can swim as well as fly.";
            strings.strInstantMines = L"Instant Mines";
            strings.hintInstantMines = L"\nAll mines will detonate instantly, even those dropped by the player.";
            strings.strHerd = L"Herd weapon";
            strings.hintHerd = L"\nLaunch multiple of the same weapon.";
            strings.strDisableBackflip = L"Disable Backflip";
            strings.hintDisableBackflip = L"\nBackflips are no longer possible.";
            strings.strDisableUnlockedAim = L"Disable Unlocked Aim";
            strings.hintDisableUnlockedAim = L"\nYou can no longer adjust the aim when firing or using the Blow Torch.";
            break;

        case 3: // es
            strings.strExtendedOptions = L"Opciones de Juego Extendidas";
            strings.strGodMode = L"Invencibilidad";
            strings.strHighJump = L"Salto alto";
            strings.strSheepHeaven = L"Paraíso de las ovejas";
            strings.strSuperShopperCrates = L"Cajas de armas secretas";
            strings.strExtendedFusesHerds = L"Extensión a retardos/manadas";
            strings.strUtilitiesDontEndTurn = L"Las herramientas no terminan el turno";
            strings.strWeaponsDontEndTurn = L"Usar armas no concluye el turno";
            strings.strLossOfControlDoesntEndTurn = L"Perder el control no concluye el turno";
            strings.strWormSelectAfterMovement = L"Nunca cancelar la selección de Worms";
            strings.strLowGravity = L"Baja gravedad";
            strings.strPersistentRope = L"Cuerda y puenting siguen enganchados";
            strings.strRapidPlay = L"Juego rápido";
            strings.strIndestructibleTerrain = L"Terreno indestructible";
            strings.strInvisibleTerrain = L"Terreno invisible";
            strings.strFastCrates = L"Cajas rápidas";
            strings.strCrateSpy = L"Espía de cajas";
            strings.strCrateLimit = L"Máximo número de cajas en el mapa a la vez";
            strings.strCrateRate = L"Frecuencia de cajas";
            strings.strSuicideBomber = L"Kamikaze -> Bomba suicida";
            strings.strAquaSheep = L"Oveja acuática";
            strings.strInstantMines = L"Minas instantáneas";
            strings.strHerd = L"Manada";
            strings.strDisableBackflip = L"Desactivar salto hacia atrás";
            strings.strDisableUnlockedAim = L"Desactivar apuntado libre al disparar";
            break;

        case 4: // es-419
            strings.strExtendedOptions = L"Opciones extendidas";
            strings.strGodMode = L"Modo Dios";
            strings.strHighJump = L"Salto alto";
            strings.strSheepHeaven = L"Paraíso de las ovejas";
            strings.strSuperShopperCrates = L"Cajas de armas secretas";
            strings.strExtendedFusesHerds = L"Mechas/rebaños ampliados";
            strings.strUtilitiesDontEndTurn = L"Las herramientas no terminan el turno";
            strings.strWeaponsDontEndTurn = L"Las armas no terminan el turno";
            strings.strLossOfControlDoesntEndTurn = L"Perder el control no termina el turno";
            strings.strWormSelectAfterMovement = L"Seleccionar gusano después de moverse";
            strings.strLowGravity = L"Gravedad baja";
            strings.strPersistentRope = L"Cuerda y bungee siguen sujetos";
            strings.strRapidPlay = L"Juego rápido";
            strings.strIndestructibleTerrain = L"Terreno indestructible";
            strings.strInvisibleTerrain = L"Terreno invisible";
            strings.strFastCrates = L"Cajas rápidas";
            strings.strCrateSpy = L"Espía de cajas";
            strings.strCrateLimit = L"Límite de cajas";
            strings.strCrateRate = L"Frecuencia de cajas";
            strings.strSuicideBomber = L"Camicace -> Atacante suicida";
            strings.strAquaSheep = L"Oveja acuática";
            strings.strInstantMines = L"Minas instantáneas";
            strings.strHerd = L"Arma de rebaño";
            strings.strDisableBackflip = L"Desactivar salto hacia atrás";
            strings.strDisableUnlockedAim = L"Desactivar mira libre al disparar";
            break;

        case 5: // fr
            strings.strExtendedOptions = L"Options de jeu étendues";
            strings.strGodMode = L"Invincibilité";
            strings.strHighJump = L"Saut en hauteur";
            strings.strSheepHeaven = L"Paradis des moutons";
            strings.strSuperShopperCrates = L"Caisses d'armes secrètes";
            strings.strExtendedFusesHerds = L"Détonateurs et troupeaux étendus";
            strings.strUtilitiesDontEndTurn = L"Les outils ne terminent pas le tour";
            strings.strWeaponsDontEndTurn = L"Utiliser une arme ne met pas fin au tour";
            strings.strLossOfControlDoesntEndTurn = L"Perdre le contrôle ne met pas fin de tour";
            strings.strWormSelectAfterMovement = L"Sélection de ver permanente";
            strings.strLowGravity = L"Faible pesanteur";
            strings.strPersistentRope = L"Corde et élastique restent attachés";
            strings.strRapidPlay = L"Partie rapide";
            strings.strIndestructibleTerrain = L"Terrain indestructible";
            strings.strInvisibleTerrain = L"Terrain invisible";
            strings.strFastCrates = L"Caisses rapides";
            strings.strCrateSpy = L"Contenu des caisses";
            strings.strCrateLimit = L"Nombre maximal de caisses simultanées";
            strings.strCrateRate = L"Taux de caisses";
            strings.strSuicideBomber = L"Kamikaze -> Bombardier kamikaze";
            strings.strAquaSheep = L"Mouton aquatique";
            strings.strInstantMines = L"Mines instantanées";
            strings.strHerd = L"Troupeau";
            strings.strDisableBackflip = L"Désactiver le salto arrière";
            strings.strDisableUnlockedAim = L"Désactiver la visée libre pendant le tir";
            break;

        case 6: // is
            strings.strExtendedOptions = L"Aukastillingar";
            strings.strGodMode = L"Guðshamur";
            strings.hintGodMode = L"\nOrmarnir eru ósærandi, nema þegar þeir drukkna í vatni.";
            strings.strHighJump = L"Hátt stökk";
            strings.hintHighJump = L"\nGerir þér kleift að stökkva hærra.";
            strings.strSheepHeaven = L"Kindaparadís";
            strings.hintSheepHeaven = L"\nKassarnir innihalda kindavopn og flugtími Ofurkindarinnar lengist.";
            strings.strSuperShopperCrates = L"Super Shopper kassar";
            strings.hintSuperShopperCrates = L"\nLætur Super Shopper kassa með leyndarmálavopnum birtast.";
            strings.strExtendedFusesHerds = L"Lengri hvellþræðir/Hjarðir";
            strings.hintExtendedFusesHerds = L"Gerir þér kleift að nota tölustafi 1-9, í stað 1-5, til að stilla hvellþræði vopna og stærð dýrahjarða.";
            strings.strUtilitiesDontEndTurn = L"Verkfæri ljúka ekki umferð";
            strings.hintUtilitiesDontEndTurn = L"Notaðu þessi verkfæri án þess að ljúka umferðinni þinni:\n\n Logsuðutæki, Loftbor, Stálbiti, Fjarflutningur.";
            strings.strWeaponsDontEndTurn = L"Vopn ljúka ekki umferð";
            strings.hintWeaponsDontEndTurn = L"\nGerir þér kleift að nota ÖLL vopn mörgum sinnum í sömu umferð.";
            strings.strLossOfControlDoesntEndTurn = L"Stjórnlost lýkur ekki umferð";
            strings.hintLossOfControlDoesntEndTurn = L"Atburðir sem valda því að þú missir stjórn hafa enn þau áhrif, en þú færð stjórnina aftur án þess að núverandi umferð ljúki.";
            strings.strWormSelectAfterMovement = L"Ormaval eftir hreyfingu";
            strings.hintWormSelectAfterMovement = L"\nÞú getur skipt yfir í aðra orma eftir að hafa hreyft einn.";
            strings.strLowGravity = L"Lítill þyngdarkraftur";
            strings.hintLowGravity = L"\nDregur úr þyngdarkrafti.";
            strings.strPersistentRope = L"Varanlegt reipi";
            strings.hintPersistentRope = L"Eftir að umferðinni þinni lýkur verða ormar sem eru fastir í Ninjareipi enn fastir, og þeir sem nota Teygjustökk verða enn í því.";
            strings.strRapidPlay = L"Hraðspilun";
            strings.hintRapidPlay = L"\nFjarlægir margar tafir og pásur til að flýta leiknum.";
            strings.strIndestructibleTerrain = L"Óeyðileggjandi landslag";
            strings.hintIndestructibleTerrain = L"Virkjar óeyðileggjandi landslag. Athugið: Farðu varlega þegar þú velur landslag til að spila á!";
            strings.strInvisibleTerrain = L"Ósýnilegt landslag";
            strings.hintInvisibleTerrain = L"\nForgrunnurinn er ekki lengur sýnilegur.";
            strings.strFastCrates = L"Hraðir kassar";
            strings.hintFastCrates = L"\nKassarnir hrapa mun hraðar af hvolfi.";
            strings.strCrateSpy = L"Kassanósari";
            strings.hintCrateSpy = L"\nSjáðu hvað er innan í kössunum.";
            strings.strCrateLimit = L"Kassahámark";
            strings.hintCrateLimit = L"\nLeikurinn mun ekki búa til kassa ef það fari fram úr þessu hámarki.";
            strings.strCrateRate = L"Kassatíðni";
            strings.hintCrateRate = L"Tilgreinir hversu margir kassar geta mögulega birst samtímis í upphafi umferðar. Ef líkur á kassafalli eru stilltar á 100% birtist nákvæmlega tilgreint magn.";
            strings.strSuicideBomber = L"Sjálfsmorðssprengjumaður";
            strings.hintSuicideBomber = L"\nKamikaze breytist í Sjálfsmorðssprengjumann.";
            strings.strAquaSheep = L"Vatnakind";
            strings.hintAquaSheep = L"Breytir hvaða Ofurkind sem er í VATNAKIND, sem getur bæði synt og flogið.";
            strings.strInstantMines = L"Trafarstundarnámur";
            strings.hintInstantMines = L"Allar námur munu springa samstundis, meira að segja þær sem leikmaðurinn kastar.";
            strings.strHerd = L"Vopnahjörð";
            strings.hintHerd = L"\nSkýtur mörgum einingum af sama vopni.";
            strings.strDisableBackflip = L"Afturábaksstökk óvirkt";
            strings.hintDisableBackflip = L"\nAfturábaksstökk eru ekki lengur möguleg.";
            strings.strDisableUnlockedAim = L"Frjáls miðun óvirk";
            strings.hintDisableUnlockedAim = L"Ekkert er lengur hægt að stilla miðunina þegar skotið er eða logsuðutækið notað.";
            break;

        case 7: // it
            strings.strExtendedOptions = L"Opzioni estese";
            strings.strGodMode = L"Invincibilità";
            strings.strHighJump = L"Salto alto";
            strings.strSheepHeaven = L"Paradiso delle pecore";
            strings.strSuperShopperCrates = L"Casse di armi segrete";
            strings.strExtendedFusesHerds = L"Micce/greggi estesi";
            strings.strUtilitiesDontEndTurn = L"Gli strumenti non terminano il turno";
            strings.strWeaponsDontEndTurn = L"Le armi non terminano il turno";
            strings.strLossOfControlDoesntEndTurn = L"La perdita di controllo non termina il turno";
            strings.strWormSelectAfterMovement = L"Selezione del verme dopo il movimento";
            strings.strLowGravity = L"Bassa gravità";
            strings.strPersistentRope = L"Corda persistente";
            strings.strRapidPlay = L"Gioco rapido";
            strings.strIndestructibleTerrain = L"Terreno indistruttibile";
            strings.strInvisibleTerrain = L"Terreno invisibile";
            strings.strFastCrates = L"Casse veloci";
            strings.strCrateSpy = L"Cassa spia";
            strings.strCrateLimit = L"Limite di casse";
            strings.strCrateRate = L"Frequenza delle casse";
            strings.strSuicideBomber = L"Kamikaze -> Suicidio tossico";
            strings.strAquaSheep = L"Pecora acquatica";
            strings.strInstantMines = L"Mine istantanee";
            strings.strHerd = L"Mandria";
            strings.strDisableBackflip = L"Disabilita il salto all'indietro";
            strings.strDisableUnlockedAim = L"Disabilita la mira libera durante il tiro";
            break;

        case 8: // nl
            strings.strExtendedOptions = L"Uitgebreide opties";
            strings.strGodMode = L"Onoverwinnelijk";
            strings.strHighJump = L"Hoge sprong";
            strings.strSheepHeaven = L"Schapenparadijs";
            strings.strSuperShopperCrates = L"Kratten met geheime wapens";
            strings.strExtendedFusesHerds = L"Uitgebreide lonten/kuddes";
            strings.strUtilitiesDontEndTurn = L"Hulpmiddelen beëindigen beurt niet";
            strings.strWeaponsDontEndTurn = L"Wapens beëindigen beurt niet";
            strings.strLossOfControlDoesntEndTurn = L"Controleverlies beëindigt beurt niet";
            strings.strWormSelectAfterMovement = L"Worm kiezen na verplaatsing";
            strings.strLowGravity = L"Minder zwaarte";
            strings.strPersistentRope = L"Touw en bungee blijven vastzitten";
            strings.strRapidPlay = L"Snel spelen";
            strings.strIndestructibleTerrain = L"Onverwoestbaar terrein";
            strings.strInvisibleTerrain = L"Onzichtbaar terrein";
            strings.strFastCrates = L"Snelle kratten";
            strings.strCrateSpy = L"Krattenspion";
            strings.strCrateLimit = L"Krattenlimiet";
            strings.strCrateRate = L"Krattenfrequentie";
            strings.strSuicideBomber = L"Kamikaze -> Zelfmoordaanval";
            strings.strAquaSheep = L"Waterschaap";
            strings.strInstantMines = L"Onmiddellijk ontploffende mijnen";
            strings.strHerd = L"Kudde";
            strings.strDisableBackflip = L"Achterwaartse salto uitschakelen";
            strings.strDisableUnlockedAim = L"Vrij richten tijdens vuren uitschakelen";
            break;

        case 9: // pl - Credit: darekols
            strings.strExtendedOptions = L"Opcje Rozszerzone";
            strings.strGodMode = L"Tryb Nieśmiertelności";
            strings.hintGodMode = L"\nRobaki nie otrzymują obrażeń, ale mogą tonąć.";
            strings.strHighJump = L"Wyższy Skok";
            strings.hintHighJump = L"\nRobaki skaczą wyżej.";
            strings.strSheepHeaven = L"Owcze Niebo";
            strings.hintSheepHeaven = L"\nZasobniki zawierają Owcze bronie oraz czas lotu Super Owcy jest wydłużony.";
            strings.strSuperShopperCrates = L"Ulepszone Zasobniki do Shoppera";
            strings.hintSuperShopperCrates = L"\nGeneruje zasobniki, które zawierają tajne bronie.";
            strings.strExtendedFusesHerds = L"Rozszerzony Lont/Stado";
            strings.hintExtendedFusesHerds = L"Pozwala na użycie klawiszy numerycznych od 1 do 9 zamiast od 1 do 5, aby zmienić czas detonacji granatów lub zmienić rozmiar stada.";
            strings.strUtilitiesDontEndTurn = L"\nNarzędzia nie kończą tury";
            strings.hintUtilitiesDontEndTurn = L"Te narzędzia nie będą kończyć tury:\n\nPalnik, Młot Pneumatyczny, Belka, Teleportacja.";
            strings.strWeaponsDontEndTurn = L"Bronie nie kończą tury";
            strings.hintWeaponsDontEndTurn = L"\nPozwala na użycie WSZYSTKICH broni kilkukrotnie w trakcie jednej tury.";
            strings.strLossOfControlDoesntEndTurn = L"Utrata kontroli nie kończy tury";
            strings.hintLossOfControlDoesntEndTurn = L"Wydarzenia, które powodują utratę kontroli nadal wywołają skutki, ale sterowanie zostanie przywrócone bez utraty tury.";
            strings.strWormSelectAfterMovement = L"Wybór Robala po poruszeniu się";
            strings.hintWormSelectAfterMovement = L"\nMożesz zmienić Robala po przemieszczeniu się.";
            strings.strLowGravity = L"Niska Grawitacja";
            strings.hintLowGravity = L"\nObniża grawitację.";
            strings.strPersistentRope = L"Trwała Lina";
            strings.hintPersistentRope = L"Po ukończeniu tury, robaki wiszące na Ninja Linie lub Bungee pozostaną na nich zawieszeni.";
            strings.strRapidPlay = L"Szybka Rozgrywka";
            strings.hintRapidPlay = L"\nUsuwa wiele opóźnień oraz przerw, aby przyspieszyć rozgrywkę.";
            strings.strIndestructibleTerrain = L"Niezniszczalny Teren";
            strings.hintIndestructibleTerrain = L"Ustawia niezniszczalny teren.\n\nUwaga: Pamiętaj, aby wybrać odpowiednią planszę!";
            strings.strInvisibleTerrain = L"Niewidzialna Plansza";
            strings.hintInvisibleTerrain = L"\nPlansza nie będzie widoczna dla graczy.";
            strings.strFastCrates = L"Szybko Opadające Zasobniki";
            strings.hintFastCrates = L"\nZasobniki znacznie szybciej opadają na ziemię.";
            strings.strCrateSpy = L"Zasobnikowy Szpieg";
            strings.hintCrateSpy = L"\nPozwala zobaczyć zawartość zasobnika.";
            strings.strCrateLimit = L"Limit Zasobników";
            strings.hintCrateLimit = L"\nZasobniki nie będą się pojawiać, gdy limit zostanie przekroczony.";
            strings.strCrateRate = L"Częstotliwość Zasobników";
            strings.hintCrateRate = L"Pozwala wybrać, ile zasobników może pojawić się na początku każdej tury. Gdy częstotliwość zostanie ustawiona na 100%, z każdą turą zostanie wyczerpany limit.";
            strings.strSuicideBomber = L"Samobójca";
            strings.hintSuicideBomber = L"\nKamikadze zostanie zastąpione Eksplodującym Robakiem.";
            strings.strAquaSheep = L"Wodna Owca";
            strings.hintAquaSheep = L"Super Owca zostaje zastąpiona WODNĄ OWCĄ, która oprócz lotu pozwala również nurkować.";
            strings.strInstantMines = L"Natychmiastowe Miny";
            strings.hintInstantMines = L"Wszystkie miny ulegną detonacji natychmiast, nawet te porzucone przez graczy.";
            strings.strHerd = L"Stadne bronie";
            strings.hintHerd = L"Pozwala wybrać ilość wystrzelonej broni za jednym razem.\n\nNa przykład: 3x Dynamit - podobnie jak 3x Szalone Krowy.";
            strings.strDisableBackflip = L"Wyłącz Salto w Tył";
            strings.hintDisableBackflip = L"\nSalto w tył nie będzie możliwe.";
            strings.strDisableUnlockedAim = L"Wyłącz Swobodne Celowanie";
            strings.hintDisableUnlockedAim = L"\nCelowanie nie będzie możliwe podczas strzału lub używania Palnika.";
            break;

        case 10: // pt - Credit: rubinho146
            strings.strExtendedOptions = L"Opções Avançadas";
            strings.strGodMode = L"Modo Deus";
            strings.hintGodMode = L"\nAs minhocas são invencíveis, exceto quando se afogam na água.";
            strings.strHighJump = L"Salto alto";
            strings.hintHighJump = L"\nPermite saltar mais alto.";
            strings.strSheepHeaven = L"Paraíso de Ovelhas";
            strings.hintSheepHeaven = L"As caixas contêm armas de Ovelha e o tempo de voo da Super Ovelha é prolongado.";
            strings.strSuperShopperCrates = L"Caixas Super Shopper";
            strings.hintSuperShopperCrates = L"\nFaz aparecer caixas com armas secretas.";
            strings.strExtendedFusesHerds = L"Prolongar tempo de explosão/Manadas";
            strings.hintExtendedFusesHerds = L"Permite utilizar as teclas numéricas 1-9, em vez de apenas 1-5, para definir os tempos da explosão das armas e o tamanho das manadas de animais.";
            strings.strUtilitiesDontEndTurn = L"As ferramentas não terminam o turno";
            strings.hintUtilitiesDontEndTurn = L"Utiliza estas armas sem terminar o teu turno:\n\nMaçarico, Berbequim, Viga, Teletransporte.";
            strings.strWeaponsDontEndTurn = L"As armas não terminam o turno";
            strings.hintWeaponsDontEndTurn = L"\nPermite utilizar TODAS as armas várias vezes no mesmo turno.";
            strings.strLossOfControlDoesntEndTurn = L"A perda de controlo não termina o turno";
            strings.hintLossOfControlDoesntEndTurn = L"Os eventos que causam a perda de controlo continuarão a ter esse efeito, mas o controlo será recuperado eventualmente sem terminar o turno atual.";
            strings.strWormSelectAfterMovement = L"Seleção de Minhoca após um movimento";
            strings.hintWormSelectAfterMovement = L"\nPodes mudar para outras minhocas depois de moveres uma.";
            strings.strLowGravity = L"Gravidade Baixa";
            strings.hintLowGravity = L"\nReduz a gravidade.";
            strings.strPersistentRope = L"Corda Persistente";
            strings.hintPersistentRope = L"Após o fim dos teus turnos, as minhocas com uma Corda Ninja presa permanecerão presas e as que estiverem a utilizar o Bungee permanecerão nele.";
            strings.strRapidPlay = L"Jogo Rápido";
            strings.hintRapidPlay = L"\nRemove muitos atrasos e pausas para acelerar o jogo.";
            strings.strIndestructibleTerrain = L"Terreno Indestrutível";
            strings.hintIndestructibleTerrain = L"Ativa o terreno indestrutível.\n\nNota: Tem cuidado ao escolher o terreno onde vais jogar!";
            strings.strInvisibleTerrain = L"Terreno Invisível";
            strings.hintInvisibleTerrain = L"\nO primeiro plano deixa de estar visível.";
            strings.strFastCrates = L"Caixas Rápidas";
            strings.hintFastCrates = L"\nAs caixas caem do céu muito mais rápido.";
            strings.strCrateSpy = L"Detetive de Caixas";
            strings.hintCrateSpy = L"\nVê o que está dentro das caixas.";
            strings.strCrateLimit = L"Limite de Caixas";
            strings.hintCrateLimit = L"\nO jogo não irá gerar caixas quando isso implicar ultrapassar este limite.";
            strings.strCrateRate = L"Frequência de Caixas";
            strings.hintCrateRate = L"Especifica quantas caixas podem aparecer em simultâneo no início do turno. Com as probabilidades de queda de caixas definidas para 100%, faz aparecer exatamente a quantidade especificada.";
            strings.strSuicideBomber = L"Bombista Suicida";
            strings.hintSuicideBomber = L"\nO Kamikaze transforma-se em Bombista Suicida.";
            strings.strAquaSheep = L"Ovelha Aquática";
            strings.hintAquaSheep = L"Transforma qualquer uma das tuas Super Ovelhas em OVELHA AQUÁTICA, que pode nadar e voar.";
            strings.strInstantMines = L"Minas Instantâneas";
            strings.hintInstantMines = L"Todas as minas irão detonar instantaneamente, mesmo as que são lançadas pelo jogador.";
            strings.strHerd = L"Manada de armas";
            strings.hintHerd = L"\nLança várias unidades da mesma arma.";
            strings.strDisableBackflip = L"Desativar Salto Mortal";
            strings.hintDisableBackflip = L"\nOs saltos mortais deixam de ser possíveis.";
            strings.strDisableUnlockedAim = L"Desativar Mira Livre";
            strings.hintDisableUnlockedAim = L"\nDeixa de ser possível ajustar a mira ao disparar ou utilizar o Maçarico.";
            break;

        case 11: // pt-br - Credit: rubinho146
            strings.strExtendedOptions = L"Opções Avançadas";
            strings.strGodMode = L"Modo Deus";
            strings.hintGodMode = L"\nAs minhocas são invencíveis, exceto quando se afogam na água.";
            strings.strHighJump = L"Salto alto";
            strings.hintHighJump = L"\nPermite saltar mais alto.";
            strings.strSheepHeaven = L"Paraíso de Ovelhas";
            strings.hintSheepHeaven = L"As caixas contêm armas de Ovelha e o tempo de voo da Super Ovelha é prolongado.";
            strings.strSuperShopperCrates = L"Caixas Super Shopper";
            strings.hintSuperShopperCrates = L"\nFaz aparecer caixas com armas secretas.";
            strings.strExtendedFusesHerds = L"Prolongar tempo de explosão/Manadas";
            strings.hintExtendedFusesHerds = L"Permite utilizar as teclas numéricas 1-9, em vez de apenas 1-5, para definir os tempos da explosão das armas e o tamanho das manadas de animais.";
            strings.strUtilitiesDontEndTurn = L"As ferramentas não terminam o turno";
            strings.hintUtilitiesDontEndTurn = L"Utilize estas armas sem terminar o seu turno:\n\nMaçarico, Berbequim, Viga, Teletransporte.";
            strings.strWeaponsDontEndTurn = L"As armas não terminam o turno";
            strings.hintWeaponsDontEndTurn = L"\nPermite utilizar TODAS as armas várias vezes no mesmo turno.";
            strings.strLossOfControlDoesntEndTurn = L"A perda de controle não termina o turno";
            strings.hintLossOfControlDoesntEndTurn = L"Os eventos que causam a perda de controle continuarão tendo esse efeito, mas o controle será recuperado eventualmente sem terminar o turno atual.";
            strings.strWormSelectAfterMovement = L"Seleção de Minhoca após um movimento";
            strings.hintWormSelectAfterMovement = L"\nVocê pode mudar para outras minhocas depois de mover uma.";
            strings.strLowGravity = L"Gravidade Baixa";
            strings.hintLowGravity = L"\nReduz a gravidade.";
            strings.strPersistentRope = L"Corda Persistente";
            strings.hintPersistentRope = L"Após o fim dos seus turnos, as minhocas com uma Corda Ninja presa permanecerão presas e as que estiverem utilizando o Bungee permanecerão nele.";
            strings.strRapidPlay = L"Jogo Rápido";
            strings.hintRapidPlay = L"\nRemove muitos atrasos e pausas para acelerar o jogo.";
            strings.strIndestructibleTerrain = L"Terreno Indestrutível";
            strings.hintIndestructibleTerrain = L"Ativa o terreno indestrutível.\n\nNota: Tenha cuidado ao escolher o terreno onde você vai jogar!";
            strings.strInvisibleTerrain = L"Terreno Invisível";
            strings.hintInvisibleTerrain = L"\nO primeiro plano deixa de estar visível.";
            strings.strFastCrates = L"Caixas Rápidas";
            strings.hintFastCrates = L"\nAs caixas caem do céu muito mais rápido.";
            strings.strCrateSpy = L"Detetive de Caixas";
            strings.hintCrateSpy = L"\nVeja o que está dentro das caixas.";
            strings.strCrateLimit = L"Limite de Caixas";
            strings.hintCrateLimit = L"\nO jogo não irá gerar caixas quando isso implicar ultrapassar este limite.";
            strings.strCrateRate = L"Frequência de Caixas";
            strings.hintCrateRate = L"Especifica quantas caixas podem aparecer em simultâneo no início do turno. Com as probabilidades de queda de caixas definidas para 100%, faz aparecer exatamente a quantidade especificada.";
            strings.strSuicideBomber = L"Bombista Suicida";
            strings.hintSuicideBomber = L"\nO Kamikaze se transforma em Bombista Suicida.";
            strings.strAquaSheep = L"Ovelha Aquática";
            strings.hintAquaSheep = L"Transforma qualquer uma das suas Super Ovelhas em OVELHA AQUÁTICA, que pode nadar e voar.";
            strings.strInstantMines = L"Minas Instantâneas";
            strings.hintInstantMines = L"Todas as minas irão detonar instantaneamente, mesmo as que são lançadas pelo jogador.";
            strings.strHerd = L"Manada de armas";
            strings.hintHerd = L"\nLance várias unidades da mesma arma.";
            strings.strDisableBackflip = L"Desativar Salto Mortal";
            strings.hintDisableBackflip = L"\nOs saltos mortais deixam de ser possíveis.";
            strings.strDisableUnlockedAim = L"Desativar Mira Livre";
            strings.hintDisableUnlockedAim = L"\nDeixa de ser possível ajustar a mira ao disparar ou utilizar o Maçarico.";
            break;

        case 12: // ru
            strings.strExtendedOptions = L"Расширенные настройки игры";
            strings.strGodMode = L"Неуязвимость";
            strings.strHighJump = L"Высокий прыжок";
            strings.strSheepHeaven = L"Овечий рай";
            strings.strSuperShopperCrates = L"Ящики с секретным оружием";
            strings.strExtendedFusesHerds = L"Расш. задержки и стада";
            strings.strUtilitiesDontEndTurn = L"Инструменты не завершают ход";
            strings.strWeaponsDontEndTurn = L"Выстрелы не прекращают ход";
            strings.strLossOfControlDoesntEndTurn = L"Потеря контроля не прекращает ход";
            strings.strWormSelectAfterMovement = L"Выбор червя не отменяется";
            strings.strLowGravity = L"Низк. гравит";
            strings.strPersistentRope = L"Верёвка и банджи остаются закреплёнными";
            strings.strRapidPlay = L"Быстрая игра";
            strings.strIndestructibleTerrain = L"Неразрушимый ландшафт";
            strings.strInvisibleTerrain = L"Невидимый ландшафт";
            strings.strFastCrates = L"Быстрые ящики";
            strings.strCrateSpy = L"Шпион ящиков";
            strings.strCrateLimit = L"Максимальное число ящиков на карте";
            strings.strCrateRate = L"коэффициент выпадения ящиков";
            strings.strSuicideBomber = L"Камикадзе -> Суицид-бомба";
            strings.strAquaSheep = L"Аква-овца";
            strings.strInstantMines = L"Мгновенные мины";
            strings.strHerd = L"Стадо";
            strings.strDisableBackflip = L"Отключить сальто назад";
            strings.strDisableUnlockedAim = L"Отключить фиксацию прицела";
            break;

        case 13: // sv
            strings.strExtendedOptions = L"Utökade Spelinställningar";
            strings.strGodMode = L"Oövervinnelighet";
            strings.strHighJump = L"Höga hopp";
            strings.strSheepHeaven = L"Fårparadis";
            strings.strSuperShopperCrates = L"Lådor med hemliga vapen";
            strings.strExtendedFusesHerds = L"Utökade stubiner/flockar";
            strings.strUtilitiesDontEndTurn = L"Verktyg avslutar inte turen";
            strings.strWeaponsDontEndTurn = L"Vapenanvändning avslutar ej runda";
            strings.strLossOfControlDoesntEndTurn = L"Kontrollförlust avslutar ej runda";
            strings.strWormSelectAfterMovement = L"Maskval avbryts aldrig";
            strings.strLowGravity = L"Låg Gravitation";
            strings.strPersistentRope = L"Rep och bungy förblir fästa";
            strings.strRapidPlay = L"Snabbt spel";
            strings.strIndestructibleTerrain = L"Oförstörbar terräng";
            strings.strInvisibleTerrain = L"Osynlig terräng";
            strings.strFastCrates = L"Snabba lådor";
            strings.strCrateSpy = L"Lådspion";
            strings.strCrateLimit = L"Maximalt antal lådor på kartan samtidigt";
            strings.strCrateRate = L"Lådfrekvens";
            strings.strSuicideBomber = L"Kamikaze -> Självmordsbomb";
            strings.strAquaSheep = L"Vattenfår";
            strings.strInstantMines = L"Omedelbara minor";
            strings.strHerd = L"Hjord";
            strings.strDisableBackflip = L"Inaktivera bakåtvolt";
            strings.strDisableUnlockedAim = L"Inaktivera fritt sikte vid skott";
            break;

        case 14: // zh-Hans
            strings.strExtendedOptions = L"扩展选项";
            strings.strGodMode = L"无敌模式";
            strings.hintGodMode = L"虫虫将处于无敌状态，但掉进水里仍会死亡。";
            strings.strHighJump = L"跳的更高";
            strings.hintHighJump = L"跳得更高。";
            strings.strSheepHeaven = L"绵羊天堂";
            strings.hintSheepHeaven = L"补给箱中将出现绵羊类武器，并延长超级绵羊的飞行时间。";
            strings.strSuperShopperCrates = L"超级补给箱";
            strings.hintSuperShopperCrates = L"生成装有隐藏武器的补给箱。";
            strings.strExtendedFusesHerds = L"设置引信时间和武器数量";
            strings.hintExtendedFusesHerds = L"可使用数字键 1-9（而不再仅限 1-5）设置定时武器的引信时间和动物类武器的数量。";
            strings.strUtilitiesDontEndTurn = L"使用工具后不结束回合";
            strings.hintUtilitiesDontEndTurn = L"使用以下工具不会结束回合：喷灯、钻头、钢梁、传送。";
            strings.strWeaponsDontEndTurn = L"使用任何武器后不结束回合";
            strings.hintWeaponsDontEndTurn = L"允许在同一回合内多次使用所有武器。";
            strings.strLossOfControlDoesntEndTurn = L"操作失误后不结束该回合";
            strings.hintLossOfControlDoesntEndTurn = L"操作失误后依然保留控制权，当前回合不会结束。";
            strings.strWormSelectAfterMovement = L"移动后可切换虫虫";
            strings.hintWormSelectAfterMovement = L"移动后可切换到其他虫虫。";
            strings.strLowGravity = L"低重力";
            strings.hintLowGravity = L"降低重力。";
            strings.strPersistentRope = L"绳索持续生效";
            strings.hintPersistentRope = L"回合结束后，使用忍者绳索的虫虫仍会保持悬挂，使用蹦极绳的虫虫也会保持原状。";
            strings.strRapidPlay = L"快速游戏";
            strings.hintRapidPlay = L"减少延迟和停顿时间，加快游戏节奏。";
            strings.strIndestructibleTerrain = L"地形不可被破坏";
            strings.hintIndestructibleTerrain = L"地形无法被破坏。注意：该功能显著影响游戏策略，请谨慎选择地形！";
            strings.strInvisibleTerrain = L"地图隐形";
            strings.hintInvisibleTerrain = L"前景地图将不再显示。";
            strings.strFastCrates = L"快速补给箱";
            strings.hintFastCrates = L"补给箱从空中掉落的速度大幅加快。";
            strings.strCrateSpy = L"补给箱透视";
            strings.hintCrateSpy = L"可以查看补给箱里有什么。";
            strings.strCrateLimit = L"补给箱上限";
            strings.hintCrateLimit = L"如果生成新的补给箱超过此上限，游戏将不会继续生成补给箱。";
            strings.strCrateRate = L"补给箱生成数量";
            strings.hintCrateRate = L"指定每回合开始时最多可同时生成多少个补给箱。当补给箱掉落概率设为 100% 时，将准确生成所指定数量的补给箱。";
            strings.strSuicideBomber = L"自杀式袭击";
            strings.hintSuicideBomber = L"开启该功能后，神风特攻队将变为自杀式袭击。";
            strings.strAquaSheep = L"水中绵羊";
            strings.hintAquaSheep = L"超级绵羊升级为水中绵羊，既能飞行，也能潜水。";
            strings.strInstantMines = L"地雷瞬爆";
            strings.hintInstantMines = L"所有地雷都会立即爆炸，包括玩家自己放置的地雷。";
            strings.strHerd = L"群发武器";
            strings.hintHerd = L"一次发射多个相同武器。";
            strings.strDisableBackflip = L"禁用后空翻";
            strings.hintDisableBackflip = L"无法再进行后空翻。";
            strings.strDisableUnlockedAim = L"禁用自由瞄准";
            strings.hintDisableUnlockedAim = L"发射武器或使用喷灯时，将无法再调整瞄准方向。";
            break;

        }
        strings.strHerdDynamite = strings.strHerd + L": " + OptionResourceString(resourceModule, 4915);
        strings.strHerdMine = strings.strHerd + L": " + OptionResourceString(resourceModule, 4916);
        strings.strHerdMingVase = strings.strHerd + L": " + OptionResourceString(resourceModule, 4917);
        strings.strHerdSheep = strings.strHerd + L": " + OptionResourceString(resourceModule, 4930);
        return strings;
    }
}
